# Generated by Django 3.1.8 on 2021-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='alter_ego',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='catchphrase',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='primary_ability',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_ability',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
